// 多语言翻译常量
export interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

// 核心翻译键（所有页面共享）
const CORE_KEYS: Record<string, Record<string, string>> = {
  'zh-CN': {
    // 导航
    'nav.home': '首页',
    'nav.video': '视频创作',
    'nav.assistant': '绘影精灵',
    'nav.nodeEditor': '节点编辑器',
    'nav.avatar': '数字人',
    'nav.filmCreation': '影视创作',
    'nav.taskCenter': '任务中心',
    'nav.research': '平台研究',
    'nav.templates': '模板库',
    'nav.skills': 'AI技能',
    'nav.social': '社交中心',
    'nav.profile': '个人中心',
    'nav.settings': '设置',
    'nav.history': '历史记录',
    'nav.logout': '退出',
    
    // 通用
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.copy': '复制',
    'common.copied': '已复制',
    'common.use': '使用',
    'common.close': '关闭',
    'common.back': '返回',
    'common.more': '更多',
    'common.generate': '生成',
    'common.generating': '生成中...',
    'common.regenerate': '重新生成',
    'common.download': '下载',
    'common.share': '分享',
    'common.search': '搜索',
    'common.upload': '上传',
    'common.preview': '预览',
    'common.reset': '重置',
    'common.apply': '应用',
    'common.selectAll': '全选',
    'common.deselectAll': '取消全选',
    
    // 创作中心
    'generate.video': '视频生成',
    'generate.videoDesc': '基于 AI 生成专业的视频内容',
    'generate.image': '图片生成',
    'generate.imageDesc': '快速创建精美的图片、海报和文案作品',
    'media.wechat': '公众号·视频号',
    'media.douyin': '短视频脚本',
    'media.xiaohongshu': '小红书图文',
    'media.imageGen': '图像创作',
    'media.poster': '海报设计',
    'media.copywriting': '文案助手',
    'media.selectType': '选择创作类型',
    'media.selectDesc': '选择你想要创作的类型，我们将为你提供最合适的 AI 创作工具',
    'generate.prompt': '描述',
    'generate.enhance': '智能增强',
    'generate.style': '艺术风格',
    'generate.mood': '氛围感觉',
    'generate.filter': '滤镜效果',
    'generate.colorTheme': '颜色主色调',
    'generate.duration': '视频时长',
    'generate.resolution': '分辨率',
    'generate.ratio': '比例',
    'generate.size': '尺寸',
    'generate.quality': '质量',
    'generate.model': '模型',
    
    // 设置
    'settings.title': '设置',
    'settings.profile': '个人信息',
    'settings.appearance': '主题外观',
    'settings.preferences': '偏好设置',
    'settings.language': '语言',
    'settings.languageDesc': '选择界面显示语言',
    'settings.fontSize': '字体大小',
    'settings.fontSizeDesc': '调整界面文字大小',
    'settings.fontStyle': '字体风格',
    'settings.fontStyleDesc': '选择界面显示字体',
    'settings.theme': '主题设置',
    'settings.interface': '界面设置',
    'settings.currentTheme': '当前主题',
    'settings.fontPreview': '字体预览',
    'settings.darkMode': '暗色模式',
    'settings.darkModeDesc': '切换亮色/暗色主题',
    'settings.compactMode': '紧凑模式',
    'settings.animations': '动画效果',
    'settings.sound': '提示音',
    'settings.autoSave': '自动保存',
    'settings.quality': '默认质量',
    'settings.showTips': '显示提示',
    'settings.history': '历史记录管理',
    'settings.clearVideo': '清空视频历史',
    'settings.clearImage': '清空图片历史',
    'settings.basicInfo': '基本信息',
    'settings.username': '用户名',
    'settings.email': '邮箱',
    'settings.manageAccount': '管理账户和应用设置',
    
    // 创作面板
    'panel.proVideo': '专业视频',
    'panel.shortVideo': 'AI短视频',
    'panel.imageCreation': '图片生成',
    'panel.filmCreation': '影视创作',
    'panel.smartAssistant': '绘影精灵',
    'panel.returnHome': '返回首页',
    'panel.aiDriven': 'AI驱动',
    
    // 资产类型
    'asset.character': '角色',
    'asset.scene': '场景',
    'asset.prop': '道具',
    'asset.generated': '已生成',
    'asset.pending': '等待生成',
    'asset.prompt': '提示词',
    'asset.views': '设计参考图',
    'asset.library': '资产库',
    'asset.chat': '对话',
    
    // 任务
    'task.center': '任务中心',
    'task.progress': '进度',
    'task.status': '状态',
    'task.pending': '等待中',
    'task.processing': '处理中',
    'task.completed': '已完成',
    'task.failed': '失败',
    'task.paused': '已暂停',
    'task.cancelled': '已取消',
    'task.retry': '重试',
    'task.cancel': '取消',
    
    // 短视频
    'shortVideo.aiMode': 'AI生成',
    'shortVideo.fixedMode': '固定文案',
    'shortVideo.script': '文案',
    'shortVideo.storyboard': '分镜',
    'shortVideo.tts': '语音',
    'shortVideo.bgm': '背景音乐',
    'shortVideo.voice': '音色',
    'shortVideo.speed': '语速',
    'shortVideo.volume': '音量',
    'shortVideo.style': '视觉风格',
    'shortVideo.oneClickGenerate': '一键生成',
    'shortVideo.generateScript': '生成文案',
    'shortVideo.generateAll': '开始生成',
    
    // 字体名称
    'font.default': '默认无衬线',
    'font.rounded': '圆润',
    'font.serif': '衬线',
    'font.monospace': '等宽',
    'font.notoSans': '思源黑体',
    'font.notoSerif': '思源宋体',
    'font.lxgwWenkai': '霞鹜文楷',
    'font.maShanZheng': '马善政楷',
    'font.zcoolkuaile': '站酷快乐体',
  },
  'en-US': {
    'nav.home': 'Home',
    'nav.video': 'AI Video',
    'nav.assistant': 'Smart Assistant',
    'nav.nodeEditor': 'Node Editor',
    'nav.avatar': 'Digital Human',
    'nav.filmCreation': 'Film Creation',
    'nav.taskCenter': 'Task Center',
    'nav.research': 'Research',
    'nav.templates': 'Templates',
    'nav.skills': 'AI Skills',
    'nav.social': 'Social',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.history': 'History',
    'nav.logout': 'Logout',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.copy': 'Copy',
    'common.copied': 'Copied',
    'common.use': 'Use',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.more': 'More',
    'common.generate': 'Generate',
    'common.generating': 'Generating...',
    'common.regenerate': 'Regenerate',
    'common.download': 'Download',
    'common.share': 'Share',
    'common.search': 'Search',
    'common.upload': 'Upload',
    'common.preview': 'Preview',
    'common.reset': 'Reset',
    'common.apply': 'Apply',
    'common.selectAll': 'Select All',
    'common.deselectAll': 'Deselect All',
    'generate.video': 'Video Generation',
    'generate.videoDesc': 'Generate professional video content with AI',
    'generate.image': 'Image Generation',
    'generate.imageDesc': 'Quickly create beautiful images, posters and copywriting',
    'media.wechat': 'WeChat / Channels',
    'media.douyin': 'Short Video Script',
    'media.xiaohongshu': 'Xiaohongshu Post',
    'media.imageGen': 'Image Creation',
    'media.poster': 'Poster Design',
    'media.copywriting': 'Copy Assistant',
    'media.selectType': 'Select Creation Type',
    'media.selectDesc': 'Choose the type you want to create, we will provide the best AI tools',
    'generate.prompt': 'Prompt',
    'generate.enhance': 'Smart Enhance',
    'generate.style': 'Art Style',
    'generate.mood': 'Mood',
    'generate.filter': 'Filter',
    'generate.colorTheme': 'Color Theme',
    'generate.duration': 'Duration',
    'generate.resolution': 'Resolution',
    'generate.ratio': 'Ratio',
    'generate.size': 'Size',
    'generate.quality': 'Quality',
    'generate.model': 'Model',
    'settings.title': 'Settings',
    'settings.profile': 'Profile Info',
    'settings.appearance': 'Appearance',
    'settings.preferences': 'Preferences',
    'settings.language': 'Language',
    'settings.languageDesc': 'Select interface language',
    'settings.fontSize': 'Font Size',
    'settings.fontSizeDesc': 'Adjust text size',
    'settings.fontStyle': 'Font Style',
    'settings.fontStyleDesc': 'Select display font',
    'settings.theme': 'Theme',
    'settings.interface': 'Interface',
    'settings.currentTheme': 'Current Theme',
    'settings.fontPreview': 'Font Preview',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeDesc': 'Toggle light/dark theme',
    'settings.compactMode': 'Compact Mode',
    'settings.animations': 'Animations',
    'settings.sound': 'Sound',
    'settings.autoSave': 'Auto Save',
    'settings.quality': 'Default Quality',
    'settings.showTips': 'Show Tips',
    'settings.history': 'History Management',
    'settings.clearVideo': 'Clear Video History',
    'settings.clearImage': 'Clear Image History',
    'settings.basicInfo': 'Basic Info',
    'settings.username': 'Username',
    'settings.email': 'Email',
    'settings.manageAccount': 'Manage account and app settings',
    'panel.proVideo': 'Pro Video',
    'panel.shortVideo': 'AI Short',
    'panel.imageCreation': 'AI Image',
    'panel.filmCreation': 'Film Creation',
    'panel.smartAssistant': 'Smart Assistant',
    'panel.returnHome': 'Back to Home',
    'panel.aiDriven': 'AI Powered',
    'asset.character': 'Character',
    'asset.scene': 'Scene',
    'asset.prop': 'Prop',
    'asset.generated': 'Generated',
    'asset.pending': 'Pending',
    'asset.prompt': 'Prompt',
    'asset.views': 'Design Sheet',
    'asset.library': 'Asset Library',
    'asset.chat': 'Chat',
    'task.center': 'Task Center',
    'task.progress': 'Progress',
    'task.status': 'Status',
    'task.pending': 'Pending',
    'task.processing': 'Processing',
    'task.completed': 'Completed',
    'task.failed': 'Failed',
    'task.paused': 'Paused',
    'task.cancelled': 'Cancelled',
    'task.retry': 'Retry',
    'task.cancel': 'Cancel',
    'shortVideo.aiMode': 'AI Generate',
    'shortVideo.fixedMode': 'Fixed Script',
    'shortVideo.script': 'Script',
    'shortVideo.storyboard': 'Storyboard',
    'shortVideo.tts': 'Voice',
    'shortVideo.bgm': 'BGM',
    'shortVideo.voice': 'Voice',
    'shortVideo.speed': 'Speed',
    'shortVideo.volume': 'Volume',
    'shortVideo.style': 'Visual Style',
    'shortVideo.oneClickGenerate': 'One-Click Generate',
    'shortVideo.generateScript': 'Generate Script',
    'shortVideo.generateAll': 'Start Generate',
    'font.default': 'Default Sans',
    'font.rounded': 'Rounded',
    'font.serif': 'Serif',
    'font.monospace': 'Monospace',
    'font.notoSans': 'Noto Sans SC',
    'font.notoSerif': 'Noto Serif SC',
    'font.lxgwWenkai': 'LXGW WenKai',
    'font.maShanZheng': 'Ma Shan Zheng',
    'font.zcoolkuaile': 'ZCOOL KuaiLe',
  },
  'ja-JP': {
    'nav.home': 'ホーム',
    'nav.video': 'AI動画',
    'nav.assistant': 'スマートアシスタント',
    'nav.nodeEditor': 'ノードエディタ',
    'nav.avatar': 'デジタルヒューマン',
    'nav.filmCreation': '映像制作',
    'nav.taskCenter': 'タスクセンター',
    'nav.research': 'リサーチ',
    'nav.templates': 'テンプレート',
    'nav.skills': 'AIスキル',
    'nav.social': 'ソーシャル',
    'nav.profile': 'プロフィール',
    'nav.settings': '設定',
    'nav.history': '履歴',
    'nav.logout': 'ログアウト',
    'common.loading': '読み込み中...',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.confirm': '確認',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.copy': 'コピー',
    'common.copied': 'コピー済み',
    'common.use': '使用',
    'common.close': '閉じる',
    'common.back': '戻る',
    'common.more': 'もっと',
    'common.generate': '生成',
    'common.generating': '生成中...',
    'common.regenerate': '再生成',
    'common.download': 'ダウンロード',
    'common.share': '共有',
    'common.search': '検索',
    'common.upload': 'アップロード',
    'common.preview': 'プレビュー',
    'common.reset': 'リセット',
    'common.apply': '適用',
    'common.selectAll': '全選択',
    'common.deselectAll': '全解除',
    'generate.video': '動画生成',
    'generate.videoDesc': 'AIでプロの動画コンテンツを生成',
    'generate.image': '画像生成',
    'generate.imageDesc': '美しい画像、ポスター、コピーを素早く作成',
    'media.wechat': 'WeChat / Channels',
    'media.douyin': '短編動画スクリプト',
    'media.xiaohongshu': '小紅書',
    'media.imageGen': '画像制作',
    'media.poster': 'ポスターデザイン',
    'media.copywriting': 'コピー助手',
    'media.selectType': '作成タイプを選択',
    'media.selectDesc': '作成したいタイプを選択してください',
    'generate.prompt': 'プロンプト',
    'generate.style': 'スタイル',
    'generate.duration': '再生時間',
    'generate.resolution': '解像度',
    'generate.ratio': '比率',
    'settings.title': '設定',
    'settings.language': '言語',
    'settings.languageDesc': '表示言語を選択',
    'settings.fontSize': 'フォントサイズ',
    'settings.fontStyle': 'フォントスタイル',
    'settings.fontStyleDesc': '表示フォントを選択',
    'settings.darkMode': 'ダークモード',
    'settings.darkModeDesc': 'ライト/ダークテーマの切り替え',
    'settings.preferences': '環境設定',
    'settings.appearance': '外観',
    'settings.basicInfo': '基本情報',
    'settings.username': 'ユーザー名',
    'settings.email': 'メール',
    'settings.manageAccount': 'アカウントとアプリ設定の管理',
    'asset.character': 'キャラクター',
    'asset.scene': 'シーン',
    'asset.prop': '小道具',
    'task.center': 'タスクセンター',
    'task.completed': '完了',
    'task.failed': '失敗',
    'panel.proVideo': 'プロ動画',
    'panel.shortVideo': 'AIショート',
    'panel.imageCreation': 'AI画像',
    'panel.filmCreation': '映像制作',
    'panel.smartAssistant': 'スマートアシスタント',
    'panel.returnHome': 'ホームに戻る',
    'panel.aiDriven': 'AI搭載',
    'font.default': 'デフォルト',
    'font.notoSans': 'Noto Sans SC',
    'font.notoSerif': 'Noto Serif SC',
    'font.lxgwWenkai': 'LXGW WenKai',
  },
  'zh-TW': {
    'nav.home': '首頁',
    'nav.video': 'AI影片',
    'nav.assistant': '繪影精靈',
    'nav.nodeEditor': '節點編輯器',
    'nav.avatar': '數位人',
    'nav.filmCreation': '影視創作',
    'nav.taskCenter': '任務中心',
    'nav.research': '平台研究',
    'nav.templates': '模板庫',
    'nav.skills': 'AI技能',
    'nav.social': '社交中心',
    'nav.profile': '個人中心',
    'nav.settings': '設定',
    'nav.history': '歷史記錄',
    'nav.logout': '登出',
    'common.loading': '載入中...',
    'common.save': '儲存',
    'common.cancel': '取消',
    'common.confirm': '確認',
    'common.delete': '刪除',
    'common.edit': '編輯',
    'common.copy': '複製',
    'common.copied': '已複製',
    'common.use': '使用',
    'common.close': '關閉',
    'common.back': '返回',
    'common.more': '更多',
    'common.generate': '生成',
    'common.generating': '生成中...',
    'common.regenerate': '重新生成',
    'common.download': '下載',
    'common.share': '分享',
    'common.search': '搜尋',
    'common.upload': '上傳',
    'common.preview': '預覽',
    'common.reset': '重設',
    'common.apply': '套用',
    'common.selectAll': '全選',
    'common.deselectAll': '取消全選',
    'generate.video': '影片生成',
    'generate.videoDesc': '基於 AI 生成專業的影片內容',
    'generate.image': '圖片生成',
    'generate.imageDesc': '快速建立精美的圖片、海報和文案作品',
    'media.wechat': '公眾號·視頻號',
    'media.douyin': '短視頻腳本',
    'media.xiaohongshu': '小紅書圖文',
    'media.imageGen': '圖像創作',
    'media.poster': '海報設計',
    'media.copywriting': '文案助手',
    'media.selectType': '選擇創作類型',
    'media.selectDesc': '選擇你想要創作的類型，我們將為你提供最合適的 AI 創作工具',
    'generate.prompt': '描述',
    'generate.enhance': '智慧增強',
    'generate.style': '藝術風格',
    'generate.duration': '影片時長',
    'generate.resolution': '解析度',
    'generate.ratio': '比例',
    'generate.size': '尺寸',
    'generate.quality': '品質',
    'generate.model': '模型',
    'settings.title': '設定',
    'settings.profile': '個人資訊',
    'settings.appearance': '主題外觀',
    'settings.preferences': '偏好設定',
    'settings.language': '語言',
    'settings.languageDesc': '選擇介面顯示語言',
    'settings.fontSize': '字型大小',
    'settings.fontSizeDesc': '調整介面文字大小',
    'settings.fontStyle': '字型風格',
    'settings.fontStyleDesc': '選擇介面顯示字型',
    'settings.theme': '主題設定',
    'settings.interface': '介面設定',
    'settings.currentTheme': '目前主題',
    'settings.fontPreview': '字型預覽',
    'settings.darkMode': '暗色模式',
    'settings.darkModeDesc': '切換亮色/暗色主題',
    'settings.compactMode': '緊湊模式',
    'settings.animations': '動畫效果',
    'settings.sound': '提示音',
    'settings.autoSave': '自動儲存',
    'settings.quality': '預設品質',
    'settings.showTips': '顯示提示',
    'settings.history': '歷史記錄管理',
    'settings.clearVideo': '清空影片歷史',
    'settings.clearImage': '清空圖片歷史',
    'settings.basicInfo': '基本資訊',
    'settings.username': '使用者名稱',
    'settings.email': '電子郵件',
    'settings.manageAccount': '管理帳戶和應用設定',
    'panel.proVideo': '專業影片',
    'panel.shortVideo': 'AI短影片',
    'panel.imageCreation': 'AI圖像創作',
    'panel.filmCreation': '影視創作',
    'panel.smartAssistant': '繪影精靈',
    'panel.returnHome': '返回首頁',
    'panel.aiDriven': 'AI驅動',
    'asset.character': '角色',
    'asset.scene': '場景',
    'asset.prop': '道具',
    'asset.generated': '已生成',
    'asset.pending': '等待生成',
    'asset.prompt': '提示詞',
    'asset.views': '設計參考圖',
    'asset.library': '資產庫',
    'asset.chat': '對話',
    'task.center': '任務中心',
    'task.progress': '進度',
    'task.status': '狀態',
    'task.pending': '等待中',
    'task.processing': '處理中',
    'task.completed': '已完成',
    'task.failed': '失敗',
    'task.paused': '已暫停',
    'task.cancelled': '已取消',
    'task.retry': '重試',
    'task.cancel': '取消',
    'shortVideo.aiMode': 'AI生成',
    'shortVideo.fixedMode': '固定文案',
    'shortVideo.script': '文案',
    'shortVideo.storyboard': '分鏡',
    'shortVideo.tts': '語音',
    'shortVideo.bgm': '背景音樂',
    'shortVideo.voice': '音色',
    'shortVideo.speed': '語速',
    'shortVideo.volume': '音量',
    'shortVideo.style': '視覺風格',
    'shortVideo.oneClickGenerate': '一鍵生成',
    'shortVideo.generateScript': '生成文案',
    'shortVideo.generateAll': '開始生成',
    'font.default': '預設無襯線',
    'font.rounded': '圓潤',
    'font.serif': '襯線',
    'font.monospace': '等寬',
    'font.notoSans': '思源黑體',
    'font.notoSerif': '思源宋體',
    'font.lxgwWenkai': '霞鶩文楷',
    'font.maShanZheng': '馬善政楷',
    'font.zcoolkuaile': '站酷快樂體',
  },
  'ko-KR': {
    'nav.home': '홈',
    'nav.video': 'AI 영상',
    'nav.assistant': '스마트 어시스턴트',
    'nav.nodeEditor': '노드 에디터',
    'nav.avatar': '디지털 휴먼',
    'nav.filmCreation': '영상 제작',
    'nav.taskCenter': '작업 센터',
    'nav.research': '플랫폼 연구',
    'nav.templates': '템플릿',
    'nav.skills': 'AI 스킬',
    'nav.social': '소셜',
    'nav.settings': '설정',
    'nav.profile': '프로필',
    'common.loading': '로딩 중...',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.confirm': '확인',
    'common.delete': '삭제',
    'common.generate': '생성',
    'common.generating': '생성 중...',
    'common.back': '뒤로',
    'generate.video': '영상 생성',
    'generate.videoDesc': 'AI로 전문적인 영상 콘텐츠 생성',
    'generate.image': '이미지 생성',
    'generate.imageDesc': '아름다운 이미지, 포스터, 카피라이팅을 빠르게 제작',
    'media.wechat': 'WeChat / Channels',
    'media.douyin': '숏폼 영상 스크립트',
    'media.xiaohongshu': '샤오홍슈',
    'media.imageGen': '이미지 제작',
    'media.poster': '포스터 디자인',
    'media.copywriting': '카피 어시스턴트',
    'media.selectType': '제작 유형 선택',
    'media.selectDesc': '제작하고 싶은 유형을 선택하세요',
    'settings.title': '설정',
    'settings.language': '언어',
    'settings.fontSize': '글꼴 크기',
    'settings.fontStyle': '글꼴 스타일',
    'settings.darkMode': '다크 모드',
    'settings.basicInfo': '기본 정보',
    'settings.username': '사용자 이름',
    'settings.email': '이메일',
    'asset.character': '캐릭터',
    'asset.scene': '장면',
    'task.center': '작업 센터',
    'task.progress': '진행률',
    'task.status': '상태',
    'task.pending': '대기 중',
    'task.processing': '처리 중',
    'task.completed': '완료',
    'task.failed': '실패',
    'task.paused': '일시정지',
    'task.cancelled': '취소됨',
    'task.retry': '재시도',
    'panel.proVideo': '프로 영상',
    'panel.shortVideo': 'AI 숏 영상',
    'panel.imageCreation': 'AI 이미지',
    'panel.filmCreation': '영상 제작',
    'panel.smartAssistant': '스마트 어시스턴트',
    'panel.returnHome': '홈으로',
    'panel.aiDriven': 'AI 구동',
    'shortVideo.aiMode': 'AI 생성',
    'shortVideo.fixedMode': '고정 대본',
    'shortVideo.script': '대본',
    'shortVideo.storyboard': '스토리보드',
    'shortVideo.style': '비주얼 스타일',
    'font.default': '기본',
    'font.notoSans': 'Noto Sans SC',
  },
  'fr-FR': {
    'nav.home': 'Accueil',
    'nav.video': 'Vidéo IA',
    'nav.assistant': 'Assistant Intelligent',
    'nav.nodeEditor': 'Éditeur de Nœuds',
    'nav.avatar': 'Humain Numérique',
    'nav.filmCreation': 'Création Film',
    'nav.taskCenter': 'Centre de Tâches',
    'nav.research': 'Recherche',
    'nav.templates': 'Modèles',
    'nav.skills': 'Compétences IA',
    'nav.social': 'Social',
    'nav.settings': 'Paramètres',
    'nav.profile': 'Profil',
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.generate': 'Générer',
    'common.back': 'Retour',
    'generate.video': 'Génération vidéo',
    'generate.videoDesc': 'Générer du contenu vidéo professionnel avec l\'IA',
    'generate.image': 'Génération d\'image',
    'generate.imageDesc': 'Créer rapidement de belles images, affiches et textes',
    'settings.title': 'Paramètres',
    'settings.language': 'Langue',
    'settings.fontSize': 'Taille de police',
    'settings.fontStyle': 'Style de police',
    'settings.darkMode': 'Mode sombre',
    'settings.basicInfo': 'Informations de base',
    'settings.username': 'Nom d\'utilisateur',
    'settings.email': 'E-mail',
    'asset.character': 'Personnage',
    'asset.scene': 'Scène',
    'task.center': 'Centre de Tâches',
    'task.completed': 'Terminé',
    'panel.proVideo': 'Vidéo Pro',
    'panel.shortVideo': 'Short IA',
    'panel.imageCreation': 'Image IA',
    'panel.filmCreation': 'Création Film',
    'panel.smartAssistant': 'Assistant Intelligent',
    'panel.returnHome': 'Retour à l\'accueil',
    'panel.aiDriven': 'Propulsé par l\'IA',
    'font.default': 'Par défaut',
  },
  'de-DE': {
    'nav.home': 'Startseite',
    'nav.video': 'KI-Video',
    'nav.assistant': 'Intelligenter Assistent',
    'nav.nodeEditor': 'Knoten-Editor',
    'nav.avatar': 'Digitaler Mensch',
    'nav.filmCreation': 'Filmerstellung',
    'nav.taskCenter': 'Aufgaben-Center',
    'nav.research': 'Forschung',
    'nav.templates': 'Vorlagen',
    'nav.skills': 'KI-Fähigkeiten',
    'nav.social': 'Soziales',
    'nav.settings': 'Einstellungen',
    'nav.profile': 'Profil',
    'common.loading': 'Laden...',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.generate': 'Generieren',
    'common.back': 'Zurück',
    'generate.video': 'Video-Generierung',
    'generate.videoDesc': 'Professionelle Videoinhalte mit KI generieren',
    'generate.image': 'Bild-Generierung',
    'generate.imageDesc': 'Schnell schöne Bilder, Poster und Texte erstellen',
    'settings.title': 'Einstellungen',
    'settings.language': 'Sprache',
    'settings.fontSize': 'Schriftgröße',
    'settings.fontStyle': 'Schriftstil',
    'settings.darkMode': 'Dunkelmodus',
    'settings.basicInfo': 'Grundinformationen',
    'settings.username': 'Benutzername',
    'settings.email': 'E-Mail',
    'asset.character': 'Charakter',
    'asset.scene': 'Szene',
    'task.center': 'Aufgaben-Center',
    'task.completed': 'Abgeschlossen',
    'panel.proVideo': 'Pro Video',
    'panel.shortVideo': 'KI-Short',
    'panel.imageCreation': 'KI-Bild',
    'panel.filmCreation': 'Filmerstellung',
    'panel.smartAssistant': 'Intelligenter Assistent',
    'panel.returnHome': 'Zurück zur Startseite',
    'panel.aiDriven': 'KI-betrieben',
    'font.default': 'Standard',
  },
  'es-ES': {
    'nav.home': 'Inicio',
    'nav.video': 'Video IA',
    'nav.assistant': 'Asistente Inteligente',
    'nav.nodeEditor': 'Editor de Nodos',
    'nav.avatar': 'Humano Digital',
    'nav.filmCreation': 'Creación de Película',
    'nav.taskCenter': 'Centro de Tareas',
    'nav.research': 'Investigación',
    'nav.templates': 'Plantillas',
    'nav.skills': 'Habilidades IA',
    'nav.social': 'Social',
    'nav.settings': 'Configuración',
    'nav.profile': 'Perfil',
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.generate': 'Generar',
    'common.back': 'Volver',
    'generate.video': 'Generación de video',
    'generate.videoDesc': 'Generar contenido de video profesional con IA',
    'generate.image': 'Generación de imagen',
    'generate.imageDesc': 'Crear rápidamente imágenes, pósters y textos hermosos',
    'settings.title': 'Configuración',
    'settings.language': 'Idioma',
    'settings.fontSize': 'Tamaño de fuente',
    'settings.fontStyle': 'Estilo de fuente',
    'settings.darkMode': 'Modo oscuro',
    'settings.basicInfo': 'Información básica',
    'settings.username': 'Nombre de usuario',
    'settings.email': 'Correo electrónico',
    'asset.character': 'Personaje',
    'asset.scene': 'Escena',
    'task.center': 'Centro de Tareas',
    'task.completed': 'Completado',
    'panel.proVideo': 'Video Pro',
    'panel.shortVideo': 'Short IA',
    'panel.imageCreation': 'Imagen IA',
    'panel.filmCreation': 'Creación de Película',
    'panel.smartAssistant': 'Asistente Inteligente',
    'panel.returnHome': 'Volver al inicio',
    'panel.aiDriven': 'Impulsado por IA',
    'font.default': 'Predeterminado',
  },
  'pt-BR': {
    'nav.home': 'Início',
    'nav.video': 'Vídeo IA',
    'nav.assistant': 'Assistente Inteligente',
    'nav.nodeEditor': 'Editor de Nós',
    'nav.avatar': 'Humano Digital',
    'nav.filmCreation': 'Criação de Filme',
    'nav.taskCenter': 'Centro de Tarefas',
    'nav.research': 'Pesquisa',
    'nav.templates': 'Modelos',
    'nav.skills': 'Habilidades IA',
    'nav.social': 'Social',
    'nav.settings': 'Configurações',
    'nav.profile': 'Perfil',
    'common.loading': 'Carregando...',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.generate': 'Gerar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.close': 'Fechar',
    'common.retry': 'Tentar novamente',
    'common.search': 'Buscar',
    'common.upload': 'Enviar',
    'common.download': 'Baixar',
    'common.copy': 'Copiar',
    'common.paste': 'Colar',
    'video.generate': 'Gerar Vídeo',
    'video.duration': 'Duração',
    'video.ratio': 'Proporção',
    'video.style': 'Estilo',
    'video.prompt': 'Prompt',
    'video.model': 'Modelo',
    'image.generate': 'Gerar Imagem',
    'image.size': 'Tamanho',
    'image.style': 'Estilo',
    'film.creation': 'Criação Cinematográfica',
    'film.character': 'Personagem',
    'film.scene': 'Cena',
    'film.storyboard': 'Storyboard',
    'film.dialogue': 'Diálogo',
    'assistant.title': 'Assistente Inteligente',
    'assistant.input': 'Digite sua ideia...',
    'assistant.send': 'Enviar',
    'assistant.generating': 'Gerando...',
    'assistant.cancel': 'Cancelar Geração',
    'settings.appearance': 'Aparência',
    'settings.language': 'Idioma',
    'settings.font': 'Fonte',
    'settings.fontSize': 'Tamanho da Fonte',
    'settings.darkMode': 'Modo Escuro',
    'settings.email': 'E-mail',
    'asset.character': 'Personagem',
    'asset.scene': 'Cena',
    'task.center': 'Centro de Tarefas',
    'task.completed': 'Concluído',
    'generate.video': 'Geração de Vídeo',
    'generate.videoDesc': 'Gerar conteúdo de vídeo profissional com IA',
    'generate.image': 'Geração de Imagem',
    'generate.imageDesc': 'Criar rapidamente imagens, pôsteres e textos bonitos',
    'panel.proVideo': 'Vídeo Pro',
    'panel.shortVideo': 'Short IA',
    'panel.imageCreation': 'Imagem IA',
    'panel.filmCreation': 'Criação de Filme',
    'panel.smartAssistant': 'Assistente Inteligente',
    'panel.returnHome': 'Voltar ao início',
    'panel.aiDriven': 'Powered by IA',
    'font.default': 'Padrão',
  },
  'it-IT': {
    'nav.home': 'Home',
    'nav.video': 'Video IA',
    'nav.assistant': 'Assistente Intelligente',
    'nav.nodeEditor': 'Editor Nodi',
    'nav.avatar': 'Umano Digitale',
    'nav.filmCreation': 'Creazione Film',
    'nav.taskCenter': 'Centro Attività',
    'nav.research': 'Ricerca',
    'nav.templates': 'Modelli',
    'nav.skills': 'Competenze IA',
    'nav.social': 'Social',
    'nav.settings': 'Impostazioni',
    'nav.profile': 'Profilo',
    'common.loading': 'Caricamento...',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.confirm': 'Conferma',
    'common.generate': 'Genera',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.close': 'Chiudi',
    'common.retry': 'Riprova',
    'common.search': 'Cerca',
    'common.upload': 'Carica',
    'common.download': 'Scarica',
    'common.copy': 'Copia',
    'common.paste': 'Incolla',
    'video.generate': 'Genera Video',
    'video.duration': 'Durata',
    'video.ratio': 'Rapporto',
    'video.style': 'Stile',
    'video.prompt': 'Prompt',
    'video.model': 'Modello',
    'image.generate': 'Genera Immagine',
    'image.size': 'Dimensione',
    'image.style': 'Stile',
    'film.creation': 'Creazione Cinematografica',
    'film.character': 'Personaggio',
    'film.scene': 'Scena',
    'film.storyboard': 'Storyboard',
    'film.dialogue': 'Dialogo',
    'assistant.title': 'Assistente Intelligente',
    'assistant.input': 'Inserisci la tua idea...',
    'assistant.send': 'Invia',
    'assistant.generating': 'Generazione...',
    'assistant.cancel': 'Annulla Generazione',
    'settings.appearance': 'Aspetto',
    'settings.language': 'Lingua',
    'settings.font': 'Font',
    'settings.fontSize': 'Dimensione Font',
    'settings.darkMode': 'Modalità Scura',
    'settings.email': 'E-mail',
    'asset.character': 'Personaggio',
    'asset.scene': 'Scena',
    'task.center': 'Centro Attività',
    'task.completed': 'Completato',
    'generate.video': 'Generazione Video',
    'generate.videoDesc': 'Generare contenuti video professionali con l\'IA',
    'generate.image': 'Generazione Immagine',
    'generate.imageDesc': 'Creare rapidamente immagini, poster e testi belli',
    'panel.proVideo': 'Video Pro',
    'panel.shortVideo': 'Short IA',
    'panel.imageCreation': 'Immagine IA',
    'panel.filmCreation': 'Creazione Film',
    'panel.smartAssistant': 'Assistente Intelligente',
    'panel.returnHome': 'Torna alla Home',
    'panel.aiDriven': 'Powered by IA',
    'font.default': 'Predefinito',
  },
  'ru-RU': {
    'nav.home': 'Главная',
    'nav.video': 'ИИ Видео',
    'nav.assistant': 'Умный Помощник',
    'nav.nodeEditor': 'Редактор Узлов',
    'nav.avatar': 'Цифровой Человек',
    'nav.filmCreation': 'Создание Фильма',
    'nav.taskCenter': 'Центр Задач',
    'nav.research': 'Исследования',
    'nav.templates': 'Шаблоны',
    'nav.skills': 'ИИ Навыки',
    'nav.social': 'Социальное',
    'nav.settings': 'Настройки',
    'nav.profile': 'Профиль',
    'common.loading': 'Загрузка...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.confirm': 'Подтвердить',
    'common.generate': 'Создать',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.close': 'Закрыть',
    'common.retry': 'Повторить',
    'common.search': 'Поиск',
    'common.upload': 'Загрузить',
    'common.download': 'Скачать',
    'common.copy': 'Копировать',
    'common.paste': 'Вставить',
    'video.generate': 'Создать Видео',
    'video.duration': 'Длительность',
    'video.ratio': 'Пропорции',
    'video.style': 'Стиль',
    'video.prompt': 'Промпт',
    'video.model': 'Модель',
    'image.generate': 'Создать Изображение',
    'image.size': 'Размер',
    'image.style': 'Стиль',
    'film.creation': 'Кинематограф',
    'film.character': 'Персонаж',
    'film.scene': 'Сцена',
    'film.storyboard': 'Раскадровка',
    'film.dialogue': 'Диалог',
    'assistant.title': 'Умный Помощник',
    'assistant.input': 'Введите идею...',
    'assistant.send': 'Отправить',
    'assistant.generating': 'Генерация...',
    'assistant.cancel': 'Отменить Генерацию',
    'settings.appearance': 'Внешний вид',
    'settings.language': 'Язык',
    'settings.font': 'Шрифт',
    'settings.fontSize': 'Размер Шрифта',
    'settings.darkMode': 'Тёмный Режим',
    'settings.email': 'Эл. почта',
    'asset.character': 'Персонаж',
    'asset.scene': 'Сцена',
    'task.center': 'Центр Задач',
    'task.completed': 'Завершено',
    'generate.video': 'Генерация Видео',
    'generate.videoDesc': 'Создавать профессиональный видеоконтент с ИИ',
    'generate.image': 'Генерация Изображений',
    'generate.imageDesc': 'Быстро создавать красивые изображения, постеры и тексты',
    'panel.proVideo': 'Про Видео',
    'panel.shortVideo': 'ИИ Шорт',
    'panel.imageCreation': 'ИИ Изображение',
    'panel.filmCreation': 'Создание Фильма',
    'panel.smartAssistant': 'Умный Помощник',
    'panel.returnHome': 'Вернуться на главную',
    'panel.aiDriven': 'На базе ИИ',
    'font.default': 'По умолчанию',
  },
  'ar-SA': {
    'nav.home': 'الرئيسية',
    'nav.video': 'فيديو ذكي',
    'nav.assistant': 'مساعد ذكي',
    'nav.nodeEditor': 'محرر العقد',
    'nav.avatar': 'إنسان رقمي',
    'nav.filmCreation': 'إنتاج سينمائي',
    'nav.taskCenter': 'مركز المهام',
    'nav.research': 'البحث',
    'nav.templates': 'القوالب',
    'nav.skills': 'مهارات الذكاء',
    'nav.social': 'اجتماعي',
    'nav.settings': 'الإعدادات',
    'nav.profile': 'الملف الشخصي',
    'common.loading': 'جارٍ التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.generate': 'إنشاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.close': 'إغلاق',
    'common.retry': 'إعادة المحاولة',
    'common.search': 'بحث',
    'common.upload': 'رفع',
    'common.download': 'تنزيل',
    'common.copy': 'نسخ',
    'common.paste': 'لصق',
    'video.generate': 'إنشاء فيديو',
    'video.duration': 'المدة',
    'video.ratio': 'النسبة',
    'video.style': 'النمط',
    'video.prompt': 'الموجه',
    'video.model': 'النموذج',
    'image.generate': 'إنشاء صورة',
    'image.size': 'الحجم',
    'image.style': 'النمط',
    'film.creation': 'إنتاج سينمائي',
    'film.character': 'شخصية',
    'film.scene': 'مشهد',
    'film.storyboard': 'لوحة القصة',
    'film.dialogue': 'حوار',
    'assistant.title': 'مساعد ذكي',
    'assistant.input': 'أدخل فكرتك...',
    'assistant.send': 'إرسال',
    'assistant.generating': 'جارٍ الإنشاء...',
    'assistant.cancel': 'إلغاء الإنشاء',
    'settings.appearance': 'المظهر',
    'settings.language': 'اللغة',
    'settings.font': 'الخط',
    'settings.fontSize': 'حجم الخط',
    'settings.darkMode': 'الوضع الداكن',
    'settings.email': 'البريد الإلكتروني',
    'asset.character': 'شخصية',
    'asset.scene': 'مشهد',
    'task.center': 'مركز المهام',
    'task.completed': 'مكتمل',
    'generate.video': 'إنشاء فيديو',
    'generate.videoDesc': 'إنشاء محتوى فيديو احترافي بالذكاء الاصطناعي',
    'generate.image': 'إنشاء صورة',
    'generate.imageDesc': 'إنشاء صور وملصقات ونصوص جميلة بسرعة',
    'panel.proVideo': 'فيديو احترافي',
    'panel.shortVideo': 'فيديو قصير ذكي',
    'panel.imageCreation': 'صورة ذكية',
    'panel.filmCreation': 'إنتاج سينمائي',
    'panel.smartAssistant': 'مساعد ذكي',
    'panel.returnHome': 'العودة للرئيسية',
    'panel.aiDriven': 'مدعوم بالذكاء الاصطناعي',
    'font.default': 'افتراضي',
  },
  'hi-IN': {
    'nav.home': 'होम',
    'nav.video': 'AI वीडियो',
    'nav.assistant': 'स्मार्ट सहायक',
    'nav.nodeEditor': 'नोड संपादक',
    'nav.avatar': 'डिजिटल मानव',
    'nav.filmCreation': 'फ़िल्म निर्माण',
    'nav.taskCenter': 'कार्य केंद्र',
    'nav.research': 'अनुसंधान',
    'nav.templates': 'टेम्पलेट',
    'nav.skills': 'AI कौशल',
    'nav.social': 'सामाजिक',
    'nav.settings': 'सेटिंग्स',
    'nav.profile': 'प्रोफ़ाइल',
    'common.loading': 'लोड हो रहा है...',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.generate': 'जनरेट करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.close': 'बंद करें',
    'common.retry': 'पुनः प्रयास',
    'common.search': 'खोजें',
    'common.upload': 'अपलोड',
    'common.download': 'डाउनलोड',
    'common.copy': 'कॉपी',
    'common.paste': 'पेस्ट',
    'video.generate': 'वीडियो जनरेट करें',
    'video.duration': 'अवधि',
    'video.ratio': 'अनुपात',
    'video.style': 'शैली',
    'video.prompt': 'प्रॉम्प्ट',
    'video.model': 'मॉडल',
    'image.generate': 'इमेज जनरेट करें',
    'image.size': 'आकार',
    'image.style': 'शैली',
    'film.creation': 'फ़िल्म निर्माण',
    'film.character': 'चरित्र',
    'film.scene': 'दृश्य',
    'film.storyboard': 'स्टोरीबोर्ड',
    'film.dialogue': 'संवाद',
    'assistant.title': 'स्मार्ट सहायक',
    'assistant.input': 'अपना विचार दर्ज करें...',
    'assistant.send': 'भेजें',
    'assistant.generating': 'जनरेट हो रहा है...',
    'assistant.cancel': 'जनरेशन रद्द करें',
    'settings.appearance': 'दिखावट',
    'settings.language': 'भाषा',
    'settings.font': 'फ़ॉन्ट',
    'settings.fontSize': 'फ़ॉन्ट आकार',
    'settings.darkMode': 'डार्क मोड',
    'settings.email': 'ईमेल',
    'asset.character': 'चरित्र',
    'asset.scene': 'दृश्य',
    'task.center': 'कार्य केंद्र',
    'task.completed': 'पूर्ण',
    'generate.video': 'वीडियो जनरेट करें',
    'generate.videoDesc': 'AI से पेशेवर वीडियो सामग्री बनाएं',
    'generate.image': 'इमेज जनरेट करें',
    'generate.imageDesc': 'जल्दी सुंदर इमेज, पोस्टर और टेक्स्ट बनाएं',
    'panel.proVideo': 'प्रो वीडियो',
    'panel.shortVideo': 'AI शॉर्ट',
    'panel.imageCreation': 'AI इमेज',
    'panel.filmCreation': 'फ़िल्म निर्माण',
    'panel.smartAssistant': 'स्मार्ट सहायक',
    'panel.returnHome': 'होम पर वापस',
    'panel.aiDriven': 'AI संचालित',
    'font.default': 'डिफ़ॉल्ट',
  },
  'th-TH': {
    'nav.home': 'หน้าแรก',
    'nav.video': 'วิดีโอ AI',
    'nav.assistant': 'ผู้ช่วยอัจฉริยะ',
    'nav.nodeEditor': 'โปรแกรมแก้ไขโหนด',
    'nav.avatar': 'ดิจิทัลฮิวแมน',
    'nav.filmCreation': 'การสร้างภาพยนตร์',
    'nav.taskCenter': 'ศูนย์งาน',
    'nav.research': 'วิจัย',
    'nav.templates': 'เทมเพลต',
    'nav.skills': 'ทักษะ AI',
    'nav.social': 'โซเชียล',
    'nav.settings': 'การตั้งค่า',
    'nav.profile': 'โปรไฟล์',
    'common.loading': 'กำลังโหลด...',
    'common.save': 'บันทึก',
    'common.cancel': 'ยกเลิก',
    'common.confirm': 'ยืนยัน',
    'common.generate': 'สร้าง',
    'common.delete': 'ลบ',
    'common.edit': 'แก้ไข',
    'common.close': 'ปิด',
    'common.retry': 'ลองอีกครั้ง',
    'common.search': 'ค้นหา',
    'common.upload': 'อัปโหลด',
    'common.download': 'ดาวน์โหลด',
    'common.copy': 'คัดลอก',
    'common.paste': 'วาง',
    'video.generate': 'สร้างวิดีโอ',
    'video.duration': 'ระยะเวลา',
    'video.ratio': 'อัตราส่วน',
    'video.style': 'สไตล์',
    'video.prompt': 'พรอมต์',
    'video.model': 'โมเดล',
    'image.generate': 'สร้างภาพ',
    'image.size': 'ขนาด',
    'image.style': 'สไตล์',
    'film.creation': 'การสร้างภาพยนตร์',
    'film.character': 'ตัวละคร',
    'film.scene': 'ฉาก',
    'film.storyboard': 'สตอรีบอร์ด',
    'film.dialogue': 'บทสนทนา',
    'assistant.title': 'ผู้ช่วยอัจฉริยะ',
    'assistant.input': 'ป้อนไอเดียของคุณ...',
    'assistant.send': 'ส่ง',
    'assistant.generating': 'กำลังสร้าง...',
    'assistant.cancel': 'ยกเลิกการสร้าง',
    'settings.appearance': 'ลักษณะ',
    'settings.language': 'ภาษา',
    'settings.font': 'แบบอักษร',
    'settings.fontSize': 'ขนาดแบบอักษร',
    'settings.darkMode': 'โหมดมืด',
    'settings.email': 'อีเมล',
    'asset.character': 'ตัวละคร',
    'asset.scene': 'ฉาก',
    'task.center': 'ศูนย์งาน',
    'task.completed': 'เสร็จสิ้น',
    'generate.video': 'สร้างวิดีโอ',
    'generate.videoDesc': 'สร้างเนื้อหาวิดีโอระดับมืออาชีพด้วย AI',
    'generate.image': 'สร้างภาพ',
    'generate.imageDesc': 'สร้างภาพ โปสเตอร์ และข้อความที่สวยงามได้อย่างรวดเร็ว',
    'panel.proVideo': 'วิดีโอโปร',
    'panel.shortVideo': 'AI ชอร์ต',
    'panel.imageCreation': 'AI ภาพ',
    'panel.filmCreation': 'การสร้างภาพยนตร์',
    'panel.smartAssistant': 'ผู้ช่วยอัจฉริยะ',
    'panel.returnHome': 'กลับหน้าแรก',
    'panel.aiDriven': 'ขับเคลื่อนด้วย AI',
    'font.default': 'ค่าเริ่มต้น',
  },
  'vi-VN': {
    'nav.home': 'Trang chủ',
    'nav.video': 'Video AI',
    'nav.assistant': 'Trợ lý Thông minh',
    'nav.nodeEditor': 'Trình chỉnh sửa Node',
    'nav.avatar': 'Người Kỹ thuật số',
    'nav.filmCreation': 'Sáng tạo Phim',
    'nav.taskCenter': 'Trung tâm Tác vụ',
    'nav.research': 'Nghiên cứu',
    'nav.templates': 'Mẫu',
    'nav.skills': 'Kỹ năng AI',
    'nav.social': 'Xã hội',
    'nav.settings': 'Cài đặt',
    'nav.profile': 'Hồ sơ',
    'common.loading': 'Đang tải...',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.generate': 'Tạo',
    'common.delete': 'Xóa',
    'common.edit': 'Sửa',
    'common.close': 'Đóng',
    'common.retry': 'Thử lại',
    'common.search': 'Tìm kiếm',
    'common.upload': 'Tải lên',
    'common.download': 'Tải xuống',
    'common.copy': 'Sao chép',
    'common.paste': 'Dán',
    'video.generate': 'Tạo Video',
    'video.duration': 'Thời lượng',
    'video.ratio': 'Tỷ lệ',
    'video.style': 'Phong cách',
    'video.prompt': 'Prompt',
    'video.model': 'Mô hình',
    'image.generate': 'Tạo Hình ảnh',
    'image.size': 'Kích thước',
    'image.style': 'Phong cách',
    'film.creation': 'Sáng tạo Phim',
    'film.character': 'Nhân vật',
    'film.scene': 'Cảnh',
    'film.storyboard': 'Bảng truyện',
    'film.dialogue': 'Hội thoại',
    'assistant.title': 'Trợ lý Thông minh',
    'assistant.input': 'Nhập ý tưởng...',
    'assistant.send': 'Gửi',
    'assistant.generating': 'Đang tạo...',
    'assistant.cancel': 'Hủy tạo',
    'settings.appearance': 'Giao diện',
    'settings.language': 'Ngôn ngữ',
    'settings.font': 'Phông chữ',
    'settings.fontSize': 'Cỡ chữ',
    'settings.darkMode': 'Chế độ Tối',
    'settings.email': 'Email',
    'asset.character': 'Nhân vật',
    'asset.scene': 'Cảnh',
    'task.center': 'Trung tâm Tác vụ',
    'task.completed': 'Hoàn thành',
    'generate.video': 'Tạo Video',
    'generate.videoDesc': 'Tạo nội dung video chuyên nghiệp bằng AI',
    'generate.image': 'Tạo Hình ảnh',
    'generate.imageDesc': 'Nhanh chóng tạo hình ảnh, áp phích và văn bản đẹp',
    'panel.proVideo': 'Video Pro',
    'panel.shortVideo': 'AI Short',
    'panel.imageCreation': 'AI Hình ảnh',
    'panel.filmCreation': 'Sáng tạo Phim',
    'panel.smartAssistant': 'Trợ lý Thông minh',
    'panel.returnHome': 'Về trang chủ',
    'panel.aiDriven': 'Động lực AI',
    'font.default': 'Mặc định',
  },
  'id-ID': {
    'nav.home': 'Beranda',
    'nav.video': 'Video AI',
    'nav.assistant': 'Asisten Cerdas',
    'nav.nodeEditor': 'Editor Node',
    'nav.avatar': 'Manusia Digital',
    'nav.filmCreation': 'Pembuatan Film',
    'nav.taskCenter': 'Pusat Tugas',
    'nav.research': 'Riset',
    'nav.templates': 'Template',
    'nav.skills': 'Keahlian AI',
    'nav.social': 'Sosial',
    'nav.settings': 'Pengaturan',
    'nav.profile': 'Profil',
    'common.loading': 'Memuat...',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.confirm': 'Konfirmasi',
    'common.generate': 'Buat',
    'common.delete': 'Hapus',
    'common.edit': 'Edit',
    'common.close': 'Tutup',
    'common.retry': 'Coba Lagi',
    'common.search': 'Cari',
    'common.upload': 'Unggah',
    'common.download': 'Unduh',
    'common.copy': 'Salin',
    'common.paste': 'Tempel',
    'video.generate': 'Buat Video',
    'video.duration': 'Durasi',
    'video.ratio': 'Rasio',
    'video.style': 'Gaya',
    'video.prompt': 'Prompt',
    'video.model': 'Model',
    'image.generate': 'Buat Gambar',
    'image.size': 'Ukuran',
    'image.style': 'Gaya',
    'film.creation': 'Pembuatan Film',
    'film.character': 'Karakter',
    'film.scene': 'Adegan',
    'film.storyboard': 'Storyboard',
    'film.dialogue': 'Dialog',
    'assistant.title': 'Asisten Cerdas',
    'assistant.input': 'Masukkan ide Anda...',
    'assistant.send': 'Kirim',
    'assistant.generating': 'Sedang membuat...',
    'assistant.cancel': 'Batalkan Pembuatan',
    'settings.appearance': 'Tampilan',
    'settings.language': 'Bahasa',
    'settings.font': 'Font',
    'settings.fontSize': 'Ukuran Font',
    'settings.darkMode': 'Mode Gelap',
    'settings.email': 'Email',
    'asset.character': 'Karakter',
    'asset.scene': 'Adegan',
    'task.center': 'Pusat Tugas',
    'task.completed': 'Selesai',
    'generate.video': 'Buat Video',
    'generate.videoDesc': 'Buat konten video profesional dengan AI',
    'generate.image': 'Buat Gambar',
    'generate.imageDesc': 'Cepat buat gambar, poster, dan teks yang indah',
    'panel.proVideo': 'Video Pro',
    'panel.shortVideo': 'AI Short',
    'panel.imageCreation': 'AI Gambar',
    'panel.filmCreation': 'Pembuatan Film',
    'panel.smartAssistant': 'Asisten Cerdas',
    'panel.returnHome': 'Kembali ke Beranda',
    'panel.aiDriven': 'Digerakkan oleh AI',
    'font.default': 'Default',
  },
};

export const TRANSLATIONS: Translations = CORE_KEYS;

// 获取翻译的辅助函数
export function t(key: string, language: string = 'zh-CN'): string {
  return TRANSLATIONS[language]?.[key] || TRANSLATIONS['zh-CN']?.[key] || key;
}
