import type { CreationCapabilitySkill } from './types';

export const sessionDeliverySkill = {
  id: 'session-delivery',
  name: '会话、增量进度与交付',
  description: '管理项目会话、任务增量事件、参考文件和结果下载，并保持 workspace 隔离。',
  sourceProject: 'LibTV Agent',
  standard: 'sceneweave-vimax-skill-v1',
  referenceMode: 'behavioral-reference',
  implementation: 'sceneweave-native',
  runtime: 'sceneweave',
  executor: 'existing-sceneweave-chain',
  inputs: ['workspaceScope', 'projectId', 'taskId', 'afterSeq', 'referenceFile'],
  outputs: ['projects', 'taskEvents', 'uploadedReference', 'downloadableResult'],
  operations: [
    {
      id: 'delivery.manage-tasks',
      name: '管理任务与会话',
      description: '复用当前 owner/workspace 隔离的任务集合。',
      runtime: 'sceneweave',
      entrypoint: '/api/tasks',
      method: 'GET',
      cost: 'no-cost',
    },
    {
      id: 'delivery.stream-task-events',
      name: '订阅增量进度',
      description: '读取当前任务的 SSE 阶段、进度、错误和完成事件。',
      runtime: 'sceneweave',
      entrypoint: '/api/tasks/:taskId/events',
      method: 'GET',
      cost: 'no-cost',
    },
    {
      id: 'delivery.upload-reference',
      name: '上传参考文件',
      description: '通过现有对象存储上传入口保存创作参考。',
      runtime: 'sceneweave',
      entrypoint: '/api/upload/material',
      method: 'POST',
      cost: 'no-cost',
      requires: ['huiying-object-storage'],
    },
    {
      id: 'delivery.download-cut-draft',
      name: '下载项目草稿',
      description: '复用制作导出接口下载最后一次可交付结果。',
      runtime: 'sceneweave',
      entrypoint: '/api/production/export',
      method: 'GET',
      cost: 'no-cost',
    },
  ],
} satisfies CreationCapabilitySkill;
