'use client';

import { useState, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { 
  FileText, 
  Camera, 
  Sparkles, 
  Copy, 
  Check, 
  CheckCircle2,
  BookOpen, 
  Zap, 
  AlertTriangle,
  ChevronDown,
  ChevronUp,
  Palette,
  Layers,
  Sun,
  Film,
  Plus,
  Trash2,
  Clock,
  Split,
  RefreshCw,
  PlayCircle,
  Save,
  Settings,
  ExternalLink,
  ArrowRight,
} from 'lucide-react';
import { generateShotsFromUserPrompt } from '@/lib/storyboard-generator';

interface VideoPromptGeneratorEnhancedProps {
  onPromptGenerated?: (prompt: string) => void;
  onApplyShots?: (shots: Array<{ prompt: string; duration: number }>) => void;
  /** 字幕段落数据 - 用于智能分镜生成 */
  subtitleSegments?: Array<{ id: string; text: string; startTime: number; endTime: number }>;
}

type SceneType = 'portrait' | 'product' | 'landscape' | 'drama';

export function VideoPromptGeneratorEnhanced({ 
  onPromptGenerated, 
  onApplyShots,
  subtitleSegments = [],
}: VideoPromptGeneratorEnhancedProps) {
  const [activeTab, setActiveTab] = useState('generator');
  
  // 分镜头相关
  const [totalDuration, setTotalDuration] = useState(15);
  const [storyboardDescription, setStoryboardDescription] = useState('');
  const [autoGeneratedShots, setAutoGeneratedShots] = useState<Array<{
    id: string;
    prompt: string;
    duration: number;
  }>>([]);

  // 字幕智能分镜相关
  const [subtitleAnalysis, setSubtitleAnalysis] = useState<{
    totalShots: number;
    dominantScene: string;
    dominantEmotion: string;
    warnings: string[];
    shotPreviews: Array<{ index: number; text: string; sceneType: string; emotion: string }>;
  } | null>(null);
  const [isGeneratingFromSubtitle, setIsGeneratingFromSubtitle] = useState(false);
  
  // 跳转确认对话框
  const [showJumpConfirmDialog, setShowJumpConfirmDialog] = useState(false);
  
  // 生成器字段
  const [generatedPrompt, setGeneratedPrompt] = useState('');
  const [copied, setCopied] = useState(false);

  // 标签页切换 - 添加分镜头模式跳转确认
  const handleTabChange = (value: string) => {
    if (value === 'storyboard' && activeTab !== 'storyboard') {
      setShowJumpConfirmDialog(true);
    } else {
      setActiveTab(value);
    }
  };

  // 确认跳转到分镜头模式
  const confirmJumpToStoryboard = () => {
    setShowJumpConfirmDialog(false);
    setActiveTab('storyboard');
  };

  // 自动生成分镜头
  const generateAutoShots = useCallback(async () => {
    if (!storyboardDescription.trim()) {
      alert('请先输入整体描述');
      return;
    }

    try {
      // 优先调用 API 获取更精准的结果
      const response = await fetch('/api/storyboard/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: storyboardDescription.trim(),
          totalDuration,
          segmentDuration: 10,
        }),
      });

      const data = await response.json();
      
      if (data.success && data.shots && data.shots.length > 0) {
        setAutoGeneratedShots(data.shots);
        
        // ★ 自动同步总时长
        const calculatedTotal = data.shots.reduce((sum: number, s: any) => sum + (s.duration || 0), 0);
        if (calculatedTotal > 0) {
          setTotalDuration(calculatedTotal);
        }
        return;
      }
    } catch (error) {
      console.warn('[Storyboard] Enhanced API调用失败，使用本地模板:', error);
    }

    // ===== 降级：使用优化引擎 v2（方案A+B+C+D+F） =====
    const userDesc = storyboardDescription.trim();
    const result = generateShotsFromUserPrompt(userDesc, totalDuration);

    setAutoGeneratedShots(result.shots);
    
    // ★ 自动同步总时长
    const fallbackTotal = result.shots.reduce((sum, s) => sum + s.duration, 0);
    if (fallbackTotal > 0) {
      setTotalDuration(fallbackTotal);
    }
  }, [storyboardDescription, totalDuration]);

  // 从字幕内容智能生成分镜（核心新功能）
  const generateShotsFromSubtitles = useCallback(async () => {
    if (!subtitleSegments || subtitleSegments.length === 0) {
      alert('没有可用的字幕数据，请先在字幕编辑器中添加内容');
      return;
    }

    setIsGeneratingFromSubtitle(true);
    
    try {
      // 调用后端 API 进行智能分镜生成
      const response = await fetch('/api/storyboard/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          segments: subtitleSegments,
          globalStyle: storyboardDescription || undefined,
          includeSourceText: true,
        }),
      });

      if (!response.ok) {
        throw new Error(`API调用失败: ${response.status}`);
      }

      const data = await response.json();

      if (data.success && data.shots && data.shots.length > 0) {
        // 应用生成的分镜头
        setAutoGeneratedShots(data.shots);
        
        // 存储分析结果用于展示
        if (data.analysis) {
          setSubtitleAnalysis({
            totalShots: data.analysis.summary.totalShots,
            dominantScene: data.analysis.summary.dominantScene,
            dominantEmotion: data.analysis.summary.dominantEmotion,
            warnings: data.analysis.warnings || [],
            shotPreviews: (data.analysis.shotDetails || []).map((d: any) => ({
              index: d.index,
              text: d.sourceText,
              sceneType: d.sceneType,
              emotion: d.emotion,
            })),
          });
        }

        console.log('[Storyboard] 字幕智能分镜生成成功:', data.shots.length, '个镜头');
      } else {
        throw new Error(data.error || '生成失败');
      }
    } catch (error) {
      console.error('[Storyboard] 字幕分镜生成失败:', error);
      
      // 降级：使用前端简化逻辑
      console.log('[Storyboard] 使用前端降级方案生成分镜...');
      const fallbackShots = generateFallbackShots(subtitleSegments);
      setAutoGeneratedShots(fallbackShots);
      setSubtitleAnalysis({
        totalShots: fallbackShots.length,
        dominantScene: '已分析',
        dominantEmotion: '已分析',
        warnings: ['使用本地降级模式生成，建议检查网络后重试以获得更精准的结果'],
        shotPreviews: subtitleSegments.map((s, i) => ({
          index: i,
          text: s.text.substring(0, 30),
          sceneType: '-',
          emotion: '-',
        })),
      });
    } finally {
      setIsGeneratingFromSubtitle(false);
    }
  }, [subtitleSegments, storyboardDescription]);

  // 前端降级生成分镜（当API不可用时）
  const generateFallbackShots = (segments: Array<{ id: string; text: string; startTime: number; endTime: number }>) => {
    return segments.map((seg, i) => ({
      id: `fallback-shot-${Date.now()}-${i}`,
      prompt: `【镜头${i + 1}】画面呈现："${seg.text}"。根据文字内容匹配的视觉场景，电影级布光和构图。${i > 0 ? '首帧延续前一镜头尾帧的动作与构图。' : ''}${i === segments.length - 1 ? '收尾镜头，画面缓缓淡出或定格。' : ''}`,
      duration: Math.min(Math.max(Math.round(seg.endTime - seg.startTime), 2), 10),
    }));
  };

  // 应用分镜头到生成界面
  const applyShotsToGenerator = () => {
    if (autoGeneratedShots.length === 0) {
      alert('请先生成分镜头');
      return;
    }

    if (onApplyShots) {
      onApplyShots(autoGeneratedShots);
    } else if (onPromptGenerated) {
      const fullPrompt = autoGeneratedShots.map((shot, i) => 
        `[镜头${i + 1} - ${shot.duration}秒] ${shot.prompt}`
      ).join('\n\n');
      onPromptGenerated(fullPrompt);
    }
    
    alert('分镜头已应用到生成界面！');
  };

  // 复制提示词
  const copyPrompt = async () => {
    try {
      await navigator.clipboard.writeText(generatedPrompt);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('复制失败:', error);
    }
  };

  return (
    <div className="space-y-6">
      {/* 主标签页 */}
      <Tabs value={activeTab} onValueChange={handleTabChange} className="w-full">
        <TabsList className="w-full grid grid-cols-3 bg-accent/30">
          <TabsTrigger value="generator" className="data-[state=active]:bg-[#EF4444] data-[state=active]:text-black">
            <Sparkles className="w-4 h-4 mr-2" />
            提示词生成器
          </TabsTrigger>
          <TabsTrigger value="storyboard" className="data-[state=active]:bg-[#EF4444] data-[state=active]:text-black">
            <Film className="w-4 h-4 mr-2" />
            分镜头助手
          </TabsTrigger>
          <TabsTrigger value="methods" className="data-[state=active]:bg-[#EF4444] data-[state=active]:text-black">
            <BookOpen className="w-4 h-4 mr-2" />
            方法库
          </TabsTrigger>
        </TabsList>

        {/* 分镜头助手 */}
        <TabsContent value="storyboard" className="space-y-6 mt-6">
          <Card className="border-border bg-gradient-to-r from-red-500/10 to-pink-500/10">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Split className="w-5 h-5 text-[#EF4444]" />
                分镜头提示词助手
              </CardTitle>
              <CardDescription>
                根据总时长自动划分分镜头，点击"应用"后才会应用到生成界面
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* 总时长和描述 */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label className="text-[#EF4444] flex items-center gap-2">
                    <Clock className="w-4 h-4" />
                    总时长（秒）
                  </Label>
                  <Input
                    type="number"
                    min={11}
                    max={300}
                    value={totalDuration}
                    onChange={(e) => setTotalDuration(Math.max(11, parseInt(e.target.value) || 15))}
                    className="bg-black/30 border-border"
                  />
                  <p className="text-xs text-muted-foreground">
                    总时长必须超过10秒，推荐15-60秒
                  </p>
                </div>
                <div className="space-y-2">
                  <Label className="text-[#EF4444]/90 flex items-center gap-2">
                    <FileText className="w-4 h-4" />
                    整体描述
                  </Label>
                  <Textarea
                    placeholder="描述整个视频的内容，例如：一个女生从海边沙滩走到栈道，欣赏日落，最后微笑面对镜头..."
                    value={storyboardDescription}
                    onChange={(e) => setStoryboardDescription(e.target.value)}
                    className="h-24 bg-black/30 border-border"
                  />
                </div>
              </div>

              {/* ===== 方式1：从字幕内容智能生成（推荐）===== */}
              {subtitleSegments && subtitleSegments.length > 0 && (
                <div className="space-y-3 p-3 bg-gradient-to-r from-green-500/10 to-red-500/10 rounded-lg border border-red-500/20">
                  <div className="flex items-center gap-2">
                    <Zap className="w-4 h-4 text-green-400" />
                    <Label className="text-green-400 text-sm font-medium">智能模式：从字幕内容生成分镜</Label>
                    <span className="text-xs text-foreground/70 ml-auto">{subtitleSegments.length}段字幕可用</span>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    根据每段字幕的文字内容，智能分析场景、情感、动作，自动规划每个分镜的画面描述
                  </p>
                  <Button
                    className="w-full bg-gradient-to-r from-red-500 to-red-500 hover:from-red-600 hover:to-orange-600 text-white"
                    onClick={generateShotsFromSubtitles}
                    disabled={isGeneratingFromSubtitle}
                  >
                    {isGeneratingFromSubtitle ? (
                      <>
                        <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                        正在分析字幕内容...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 mr-2" />
                        从字幕智能生成分镜
                      </>
                    )}
                  </Button>
                </div>
              )}

              {/* 字幕分析结果展示 */}
              {subtitleAnalysis && (
                <Card className="border-red-500/20 bg-red-500/5">
                  <CardContent className="pt-4">
                    <div className="grid grid-cols-3 gap-3 mb-3">
                      <div className="text-center">
                        <div className="text-lg font-bold text-green-400">{subtitleAnalysis.totalShots}</div>
                        <div className="text-xs text-muted-foreground">生成镜头</div>
                      </div>
                      <div className="text-center">
                        <div className="text-sm font-medium text-foreground/80">{subtitleAnalysis.dominantScene}</div>
                        <div className="text-xs text-muted-foreground">主导场景</div>
                      </div>
                      <div className="text-center">
                        <div className="text-sm font-medium text-foreground/80">{subtitleAnalysis.dominantEmotion}</div>
                        <div className="text-xs text-muted-foreground">主导情感</div>
                      </div>
                    </div>
                    {subtitleAnalysis.warnings.length > 0 && (
                      <div className="space-y-1">
                        {subtitleAnalysis.warnings.map((w, i) => (
                          <div key={i} className="text-xs text-red-400/80 flex items-start gap-1">
                            <AlertTriangle className="w-3 h-3 mt-0.5 flex-shrink-0" />
                            {w}
                          </div>
                        ))}
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}

              {/* 分隔线 */}
              {(subtitleSegments && subtitleSegments.length > 0) && (
                <div className="flex items-center gap-3 py-1">
                  <div className="flex-1 h-px bg-accent/50"></div>
                  <span className="text-xs text-foreground/30">或使用传统模式</span>
                  <div className="flex-1 h-px bg-accent/50"></div>
                </div>
              )}

              {/* ===== 方式2：传统提示词模式 ===== */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label className="text-[#EF4444] flex items-center gap-2">
                    <Clock className="w-4 h-4" />
                    总时长（秒）
                  </Label>
                  <Input
                    type="number"
                    min={11}
                    max={300}
                    value={totalDuration}
                    onChange={(e) => setTotalDuration(Math.max(11, parseInt(e.target.value) || 15))}
                    className="bg-black/30 border-border"
                  />
                  <p className="text-xs text-muted-foreground">
                    总时长必须超过10秒，推荐15-60秒
                  </p>
                </div>
                <div className="space-y-2">
                  <Label className="text-[#EF4444]/90 flex items-center gap-2">
                    <FileText className="w-4 h-4" />
                    整体描述
                  </Label>
                  <Textarea
                    placeholder="描述整个视频的内容..."
                    value={storyboardDescription}
                    onChange={(e) => setStoryboardDescription(e.target.value)}
                    className="h-[72px] bg-black/30 border-border"
                  />
                </div>
              </div>

              {/* 传统模式按钮 */}
              <Button
                className="w-full bg-gradient-to-r from-red-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white"
                onClick={generateAutoShots}
                disabled={!storyboardDescription.trim()}
              >
                <Split className="w-4 h-4 mr-2" />
                自动划分分镜头（传统模式）
              </Button>
            </CardContent>
          </Card>

          {/* 自动生成的分镜头列表 */}
          {autoGeneratedShots.length > 0 && (
            <div className="space-y-4">
              <Card className="border-border bg-accent/30">
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div>
                      <CardTitle className="text-white flex items-center gap-2">
                        <Layers className="w-5 h-5 text-[#EF4444]" />
                        自动划分的分镜头 ({autoGeneratedShots.length}段)
                      </CardTitle>
                      <CardDescription>
                        请检查并补充每个分镜头的内容，点击"应用"后才会应用到生成界面
                      </CardDescription>
                    </div>
                    <div className="text-right">
                      <div className="text-lg font-bold text-[#EF4444]">
                        {autoGeneratedShots.reduce((sum, s) => sum + s.duration, 0)}秒
                      </div>
                      <div className="text-xs text-muted-foreground">
                        每段最长{Math.max(...autoGeneratedShots.map(s => s.duration))}秒
                      </div>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  {autoGeneratedShots.map((shot, index) => (
                    <Card key={shot.id} className="border-border bg-black/30">
                      <CardHeader className="pb-2">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-3">
                            <div className="w-8 h-8 bg-[#EF4444] text-black rounded-full flex items-center justify-center font-bold text-sm">
                              {index + 1}
                            </div>
                            <div>
                              <CardTitle className="text-white text-sm">
                                分镜头 {index + 1}
                              </CardTitle>
                              <CardDescription className="text-xs">
                                {shot.duration}秒
                                {index > 0 && <span className="ml-2 text-red-400">⚠️ 请确保首帧与前一段尾帧一致</span>}
                              </CardDescription>
                            </div>
                          </div>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="text-foreground/70 hover:text-red-400"
                            onClick={() => {
                              setAutoGeneratedShots(prev => prev.filter(s => s.id !== shot.id));
                            }}
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </CardHeader>
                      <CardContent>
                        <Textarea
                          value={shot.prompt}
                          onChange={(e) => {
                            setAutoGeneratedShots(prev => prev.map(s => 
                              s.id === shot.id ? { ...s, prompt: e.target.value } : s
                            ));
                          }}
                          className="h-20 bg-black/30 border-border text-sm"
                          placeholder="请补充这个分镜头的详细描述..."
                        />
                        <div className="flex items-center justify-between mt-2">
                          <div className="flex items-center gap-2">
                            <Label className="text-muted-foreground text-xs">时长</Label>
                            <Input
                              type="number"
                              min={1}
                              max={10}
                              value={shot.duration}
                              onChange={(e) => {
                                const duration = Math.min(10, Math.max(1, parseInt(e.target.value) || 5));
                                setAutoGeneratedShots(prev => prev.map(s => 
                                  s.id === shot.id ? { ...s, duration } : s
                                ));
                              }}
                              className="w-20 h-7 bg-black/30 border-border text-xs"
                            />
                            <span className="text-muted-foreground text-xs">秒</span>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                  
                  <div className="flex gap-3 pt-2">
                    <Button
                      variant="secondary"
                      onClick={() => {
                        const newShot = {
                          id: `auto-shot-${Date.now()}`,
                          prompt: '新分镜头：',
                          duration: 5
                        };
                        setAutoGeneratedShots(prev => [...prev, newShot]);
                      }}
                      className="flex-1"
                    >
                      <Plus className="w-4 h-4 mr-2" />
                      添加分镜头
                    </Button>
                    
                    {/* 应用分镜头按钮 */}
                    <Button
                      className="flex-1 bg-gradient-to-r from-[#EF4444] to-[#B4E22F] hover:opacity-90 text-black"
                      onClick={applyShotsToGenerator}
                    >
                      <ExternalLink className="w-4 h-4 mr-2" />
                      应用到生成界面
                    </Button>
                  </div>
                </CardContent>
              </Card>

              {/* 检查清单 */}
              <Card className="border-border bg-accent/30">
                <CardHeader>
                  <CardTitle className="text-white text-base flex items-center gap-2">
                    <Check className="w-5 h-5 text-green-400" />
                    分镜头检查清单
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2 text-sm text-foreground/70">
                    <li className="flex items-start gap-2">
                      <CheckCircle2 className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                      <span>总时长超过10秒：{autoGeneratedShots.reduce((sum, s) => sum + s.duration, 0)}秒 ✓</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <CheckCircle2 className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                      <span>每段分镜头不超过10秒：最长{Math.max(...autoGeneratedShots.map(s => s.duration))}秒 ✓</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <AlertTriangle className="w-4 h-4 text-red-400 mt-0.5 flex-shrink-0" />
                      <span>请确保每段分镜头首帧与前一段尾帧一致（需要人工确认）</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <AlertTriangle className="w-4 h-4 text-red-400 mt-0.5 flex-shrink-0" />
                      <span>点击"应用到生成界面"后才会应用到视频生成</span>
                    </li>
                  </ul>
                </CardContent>
              </Card>
            </div>
          )}
        </TabsContent>

        {/* 提示词生成器 */}
        <TabsContent value="generator" className="space-y-6 mt-6">
          <Card className="border-border bg-accent/30">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-[#EF4444]" />
                提示词生成器（简化版）
              </CardTitle>
              <CardDescription>
                在此处可以看到从分镜头助手应用的提示词
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <Textarea
                  value={generatedPrompt}
                  onChange={(e) => setGeneratedPrompt(e.target.value)}
                  placeholder="在此处输入或粘贴提示词，或从分镜头助手应用..."
                  className="h-64 bg-black/30 border-border"
                />
                
                <div className="flex gap-3">
                  <Button
                    variant="secondary"
                    onClick={copyPrompt}
                    className="flex-1"
                  >
                    {copied ? (
                      <>
                        <Check className="w-4 h-4 mr-2" />
                        已复制
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4 mr-2" />
                        复制提示词
                      </>
                    )}
                  </Button>
                  
                  <Button
                    onClick={() => setGeneratedPrompt('')}
                    variant="secondary"
                    className="flex-1"
                  >
                    <Trash2 className="w-4 h-4 mr-2" />
                    清空
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* 方法库 */}
        <TabsContent value="methods" className="space-y-6 mt-6">
          <Card className="border-border bg-accent/30">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-[#EF4444]" />
                方法库（简化版）
              </CardTitle>
              <CardDescription>
                查看完整方法库请使用原组件
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                这是增强版提示词助手，主要功能：
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4">
                <li>点击"分镜头助手"时会询问是否跳转</li>
                <li>分镜头生成后需要点击"应用"才会生效</li>
                <li>应用后会自动创建未创建的分镜头</li>
              </ul>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* 跳转到分镜头模式确认对话框 */}
      <Dialog open={showJumpConfirmDialog} onOpenChange={setShowJumpConfirmDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Film className="w-5 h-5 text-red-500" />
              跳转到分镜头模式
            </DialogTitle>
            <DialogDescription>
              确定要跳转到分镜头助手吗？您可以在那里自动划分分镜头并应用到生成界面。
            </DialogDescription>
          </DialogHeader>
          
          <div className="bg-red-500/10 rounded-lg p-4 my-4">
            <h4 className="text-white font-medium mb-2">分镜头助手功能：</h4>
            <ul className="text-sm text-foreground/70 space-y-1">
              <li>• 根据总时长自动划分分镜头</li>
              <li>• 每段分镜头不超过10秒</li>
              <li>• 点击"应用"后才会应用到生成界面</li>
            </ul>
          </div>
          
          <DialogFooter className="flex gap-3">
            <Button
              variant="secondary"
              onClick={() => setShowJumpConfirmDialog(false)}
              className="flex-1"
            >
              取消
            </Button>
            <Button
              className="flex-1 bg-gradient-to-r from-red-500 to-pink-500"
              onClick={confirmJumpToStoryboard}
            >
              <ArrowRight className="w-4 h-4 mr-2" />
              是，跳转
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
